// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy-F89afQQSIsbgyMIYO8q4MxwXKWQjK8',
    appId: '1:102816750680:web:76c7d164780c1eae5cbe2d',
    messagingSenderId: '102816750680',
    projectId: 'pawlay-firebase',
    authDomain: 'pawlay-firebase.firebaseapp.com',
    storageBucket: 'pawlay-firebase.appspot.com',
    measurementId: 'G-TD3ZJRDY40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA876y_orKDr3u3HNyxDdwIXzNoVZBMbZU',
    appId: '1:102816750680:android:db13afe937d3026a5cbe2d',
    messagingSenderId: '102816750680',
    projectId: 'pawlay-firebase',
    storageBucket: 'pawlay-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwwdsfUaZ2kRisT76DdFZy4imTrP7UEjE',
    appId: '1:102816750680:ios:329f10aaa1e1baa85cbe2d',
    messagingSenderId: '102816750680',
    projectId: 'pawlay-firebase',
    storageBucket: 'pawlay-firebase.appspot.com',
    iosBundleId: 'com.example.paw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwwdsfUaZ2kRisT76DdFZy4imTrP7UEjE',
    appId: '1:102816750680:ios:329f10aaa1e1baa85cbe2d',
    messagingSenderId: '102816750680',
    projectId: 'pawlay-firebase',
    storageBucket: 'pawlay-firebase.appspot.com',
    iosBundleId: 'com.example.paw',
  );
}
